extends:
  - airbnb
  - airbnb/hooks

globals:
  document: true
  window: true

parserOptions:
  ecmaVersion: 12

root: true

rules:
  array-bracket-spacing:
    - error
    - always
  arrow-parens:
    - error
    - as-needed
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  class-methods-use-this: 0
  global-require: 0
  jsx-a11y/label-has-associated-control:
    - error
    - assert: either
  max-len:
    - error
    - 120
    - 2
    - ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  no-continue: 0
  no-mixed-operators:
    - error
    - allowSamePrecedence: true
  no-param-reassign: 0
  no-plusplus: 0
  no-underscore-dangle: 0
  no-useless-constructor: 0
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-curly-spacing:
    - error
    - when: always
      children: true
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  wrap-iife: 0

settings:
  import/resolver:
    node:
      paths:
        - .
