# Documentation for the sass-lint Linters is available at:
# https://github.com/sasstools/sass-lint/tree/master/docs/rules

options:
  formatter: stylish
  merge-default-rules: false
files:
  include: "**/*.s+(a|c)ss"
  ignore:
    - node_modules/**
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude:
      - 'breakpoint'
      - 'mq'
      - 'media-breakpoint-up'
      - 'media-breakpoint-down'

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: false
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 2
    - convention: hyphenatedbem
  function-name-format: 2
  id-name-format: 2
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 2

  # Style Guide
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    - style: stroustrup
    - allow-single-line: true
  clean-import-paths: 2
  empty-args: 0
  hex-length: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 4

  property-sort-order:
    - 1
    -
      order:
        # Heading

        - 'content'
        - 'quotes'

        # Box

        - 'display'
        - 'visibility'

        - 'position'
        - 'z-index'
        - 'top'
        - 'right'
        - 'bottom'
        - 'left'

        - 'box-sizing'

        - 'grid'
        - 'grid-after'
        - 'grid-area'
        - 'grid-auto-columns'
        - 'grid-auto-flow'
        - 'grid-auto-rows'
        - 'grid-before'
        - 'grid-column'
        - 'grid-column-end'
        - 'grid-column-gap'
        - 'grid-column-start'
        - 'grid-columns'
        - 'grid-end'
        - 'grid-gap'
        - 'grid-row'
        - 'grid-row-end'
        - 'grid-row-gap'
        - 'grid-row-start'
        - 'grid-rows'
        - 'grid-start'
        - 'grid-template'
        - 'grid-template-areas'
        - 'grid-template-columns'
        - 'grid-template-rows'

        - 'flex'
        - 'flex-basis'
        - 'flex-direction'
        - 'flex-flow'
        - 'flex-grow'
        - 'flex-shrink'
        - 'flex-wrap'
        - 'align-content'
        - 'align-items'
        - 'align-self'
        - 'justify-content'
        - 'order'

        - 'width'
        - 'min-width'
        - 'max-width'
        - 'height'
        - 'min-height'
        - 'max-height'

        - 'margin'
        - 'margin-top'
        - 'margin-right'
        - 'margin-bottom'
        - 'margin-left'

        - 'padding'
        - 'padding-top'
        - 'padding-right'
        - 'padding-bottom'
        - 'padding-left'

        - 'float'
        - 'clear'

        - 'overflow'
        - 'overflow-x'
        - 'overflow-y'

        - 'clip'
        - 'zoom'

        - 'columns'
        - 'column-gap'
        - 'column-fill'
        - 'column-rule'
        - 'column-span'
        - 'column-count'
        - 'column-width'

        - 'table-layout'
        - 'empty-cells'
        - 'caption-side'
        - 'border-spacing'
        - 'border-collapse'
        - 'list-style'
        - 'list-style-position'
        - 'list-style-type'
        - 'list-style-image'

        # Border

        - 'border'
        - 'border-top'
        - 'border-right'
        - 'border-bottom'
        - 'border-left'
        - 'border-width'
        - 'border-top-width'
        - 'border-right-width'
        - 'border-bottom-width'
        - 'border-left-width'

        - 'border-style'
        - 'border-top-style'
        - 'border-right-style'
        - 'border-bottom-style'
        - 'border-left-style'

        - 'border-radius'
        - 'border-top-left-radius'
        - 'border-top-right-radius'
        - 'border-bottom-left-radius'
        - 'border-bottom-right-radius'

        - 'border-color'
        - 'border-top-color'
        - 'border-right-color'
        - 'border-bottom-color'
        - 'border-left-color'

        - 'outline'
        - 'outline-color'
        - 'outline-offset'
        - 'outline-style'
        - 'outline-width'

        - 'stroke-width'
        - 'stroke-linecap'
        - 'stroke-dasharray'
        - 'stroke-dashoffset'
        - 'stroke'

        # Background

        - 'opacity'

        - 'background'
        - 'background-color'
        - 'background-image'
        - 'background-repeat'
        - 'background-position'
        - 'background-size'
        - 'box-shadow'
        - 'fill'

        # Text

        - 'color'

        - 'font'
        - 'font-family'
        - 'font-size'
        - 'font-size-adjust'
        - 'font-stretch'
        - 'font-effect'
        - 'font-style'
        - 'font-variant'
        - 'font-weight'

        - 'font-emphasize'
        - 'font-emphasize-position'
        - 'font-emphasize-style'

        - 'letter-spacing'
        - 'line-height'
        - 'list-style'
        - 'word-spacing'

        - 'text-align'
        - 'text-align-last'
        - 'text-decoration'
        - 'text-indent'
        - 'text-justify'
        - 'text-overflow'
        - 'text-overflow-ellipsis'
        - 'text-overflow-mode'
        - 'text-rendering'
        - 'text-outline'
        - 'text-shadow'
        - 'text-transform'
        - 'text-wrap'
        - 'word-wrap'
        - 'word-break'

        - 'text-emphasis'
        - 'text-emphasis-color'
        - 'text-emphasis-style'
        - 'text-emphasis-position'

        - 'vertical-align'
        - 'white-space'
        - 'word-spacing'
        - 'hyphens'

        - 'src'

        # Animation

        - 'transform'
        - 'transform-origin'
        - 'transform-style'
        - 'backface-visibility'
        - 'perspective'
        - 'perspective-origin'

        - 'transition'
        - 'transition-property'
        - 'transition-duration'
        - 'transition-timing-function'
        - 'transition-delay'

        - 'animation'
        - 'animation-name'
        - 'animation-duration'
        - 'animation-play-state'
        - 'animation-timing-function'
        - 'animation-delay'
        - 'animation-iteration-count'
        - 'animation-direction'

        # Other

        - 'tab-size'
        - 'counter-reset'
        - 'counter-increment'
        - 'resize'
        - 'cursor'
        - 'pointer-events'
        - 'speak'
        - 'user-select'
        - 'nav-index'
        - 'nav-up'
        - 'nav-right'
        - 'nav-down'
        - 'nav-left'

  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 0
  space-around-operator: 0

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
