extends:
  - "@wemake-services/stylelint-config-scss"

rules:
  color-format/format: null
  color-no-invalid-hex: true
  declaration-block-no-duplicate-properties: true
  max-line-length: 120
  max-nesting-depth: 6
  number-max-precision: 5
  plugin/no-low-performance-animation-properties: null
  plugin/selector-tag-no-without-class: null
  plugin/stylelint-no-indistinguishable-colors: null
  scale-unlimited/declaration-strict-value: 0
  scss/at-function-named-arguments: null
  scss/at-mixin-named-arguments: null
  scss/dollar-variable-pattern: ^[_]?[a-z]+([a-z0-9-_]+[a-z0-9]+)?$
  selector-class-pattern: ^([a-z][a-z0-9]*)(-[a-z0-9]+)*((__([a-z][a-z0-9]*)(-[a-z0-9]+)*)?(--([a-z][a-z0-9]*)(-[a-z0-9]+)*)?)*$
  selector-max-compound-selectors: 6
  selector-max-specificity: 3,3,3
