# Global settings applied to the whole site.
[build]
  base    = ""
  publish = "public"
  command = "yarn build"
  HUGO_VERSION = "0.66.0"
  NODE_VERSION = "12.13.1"
  NODE_ENV = "production"
  YARN_VERSION = "1.22.0"
  YARN_FLAGS = "--no-ignore-optional"
