[build]
  base = ""
  command = "yarn next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16.14.0"
  NODE_ENV = "production"
  YARN_VERSION = "3.3.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
