backend:
  name: github
  repo: ricardosousa10101989/ricardosousa10101989.github.io # Path to your Github repository
  branch: <% CURRENT_BRANCH %> # Branch to update (current branch dynamically set by Gulp)

media_folder: "/static/media/uploads" # Folder where user uploaded files should go
public_folder: "/media/uploads"

collections: # A list of collections the CMS should be able to edit
